[env:esp32-s3-devkitc-1]
; 현재 가장 안정된 최신 플랫폼 버전 지정
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = espidf

; --- [추가] PlatformIO 빌드 캐싱 활성화 ---
; 빌드된 바이너리 아카이브를 캐시하여 다음 빌드 시간을 획기적으로 줄입니다.
build_cache_dir = .pio/cache

; 통신 속도
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

board_build.flash_mode = dio
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi ; 보드 사양에 맞게 조정

; LovyanGFX
lib_deps =
    lovyan03/LovyanGFX @ ^1.2.0
    bblanchon/ArduinoJson @ ^6.21.5

build_flags =
    -D LGFX_USE_V1
    ; --- [변경] 컴파일러 버그를 회피하고 디스플레이 성능을 높이기 위해 -O2로 변경 ---
    -O2

    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue    

    -DCORE_DEBUG_LEVEL=3

    ; Arduino 환경을 위한 필수 매크로 (IDF 기반일 때 중요)
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

    ; --- [추가] 중복 컴포넌트 기호 충돌을 해결하기 위한 링커 플래그 ---
    -Wl,--allow-multiple-definition

    ; --- [추가] 컴파일러 속도 최적화 플래그 ---
    -pipe

    -D INCUBATOR_ENABLE_CLOUD

board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt