[env:esp32-s3-devkitc-1]
; 현재 가장 안정된 최신 플랫폼 버전 지정
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = espidf

; 통신 속도
monitor_speed = 115200

; LovyanGFX
lib_deps =
    lovyan03/LovyanGFX @ ^1.2.0

build_flags =
    -D LGFX_USE_V1
    ; Arduino 환경을 위한 필수 매크로 (IDF 기반일 때 중요)
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt